SOURCES = ../aux.ml ../constraintPolyInfer.ml ../constraintUnify.ml ../inferDefs.ml ../lexer.mll ../parser.mly ../prettyPrinter.ml ../reduce.ml ../syntax.ml \
          ../unifyFunctions/deleteRedundant.ml ../unifyFunctions/delNOLs.ml ../unifyFunctions/expressionUnification.ml ../unifyFunctions/typeUnification.ml \
          ../compiler.ml

EXEC = compiler

include ~/lib/Makefile.ocaml

CAMLC = ocamlc -g 
